
project_id = "iwwjfixonkmhhpnfkhkm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://iwwjfixonkmhhpnfkhkm.supabase.co"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[functions.ai-discovery]
verify_jwt = false

[edge_runtime]
ip_version = "ipv4"
